"""client_wm

Revision ID: 172bfb3bed7b
Revises: 
Create Date: 2022-02-01 13:58:05.125518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172bfb3bed7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_w_temp')
    op.drop_table('sqlite_sequence')
    op.alter_column('client_wm', 'date',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_wm', 'date',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.create_table('client_w_temp',
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.INTEGER(), nullable=True),
    sa.Column('breaking', sa.TEXT(), nullable=True),
    sa.Column('repair', sa.TEXT(), nullable=True),
    sa.Column('invoice', sa.INTEGER(), nullable=True),
    sa.Column('cost', sa.INTEGER(), nullable=True),
    sa.Column('profit', sa.INTEGER(), nullable=True),
    sa.Column('debt', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    # ### end Alembic commands ###
